// Courses data - centralized to avoid duplication
export const courses = [
  // Web Development Courses
  {
    id: 1,
    title: "The Complete Full-Stack Web Development Bootcamp",
    instructor: "Dr. Angela Yu, Developer and Lead Instructor",
    rating: 4.7,
    reviews: 430013,
    price: "₹449",
    originalPrice: "₹3,099",
    image: "/placeholder.svg?height=400&width=600",
    premium: true,
    bestseller: true,
    categoryId: "web-dev",
    topicIds: ["web-dev-general"],
  },
  {
    id: 2,
    title: "The Web Developer Bootcamp 2025",
    instructor: "Colt Steele",
    rating: 4.7,
    reviews: 279587,
    price: "₹499",
    originalPrice: "₹3,499",
    image: "/placeholder.svg?height=400&width=600",
    premium: true,
    categoryId: "web-dev",
    topicIds: ["web-dev-general"],
  },
  {
    id: 3,
    title: "Web Development Masterclass - Online Certification Course",
    instructor: "YouAccel Training",
    rating: 4.4,
    reviews: 10123,
    price: "₹499",
    originalPrice: "₹3,299",
    image: "/placeholder.svg?height=400&width=600",
    premium: true,
    categoryId: "web-dev",
    topicIds: ["web-dev-general"],
  },
  {
    id: 4,
    title: "The Complete Web Developer Course 3.0",
    instructor: "Rob Percival, Codestars • over 2 million students",
    rating: 4.2,
    reviews: 72445,
    price: "₹699",
    originalPrice: "₹4,999",
    image: "/placeholder.svg?height=400&width=600",
    premium: true,
    categoryId: "web-dev",
    topicIds: ["web-dev-general"],
  },
  // JavaScript Courses
  {
    id: 5,
    title: "JavaScript - The Complete Guide 2025 (Beginner + Advanced)",
    instructor: "Maximilian Schwarzmüller",
    rating: 4.6,
    reviews: 158742,
    price: "₹499",
    originalPrice: "₹3,499",
    image: "/placeholder.svg?height=400&width=600",
    premium: true,
    bestseller: true,
    categoryId: "web-dev",
    topicIds: ["javascript"],
  },
  {
    id: 6,
    title: "Modern JavaScript From The Beginning",
    instructor: "Brad Traversy",
    rating: 4.8,
    reviews: 45678,
    price: "₹449",
    originalPrice: "₹2,999",
    image: "/placeholder.svg?height=400&width=600",
    premium: true,
    categoryId: "web-dev",
    topicIds: ["javascript"],
  },
  {
    id: 7,
    title: "JavaScript: Understanding the Weird Parts",
    instructor: "Anthony Alicea",
    rating: 4.7,
    reviews: 67890,
    price: "₹399",
    originalPrice: "₹2,799",
    image: "/placeholder.svg?height=400&width=600",
    premium: true,
    categoryId: "web-dev",
    topicIds: ["javascript"],
  },
  {
    id: 8,
    title: "Advanced JavaScript Concepts",
    instructor: "Andrei Neagoie",
    rating: 4.6,
    reviews: 34567,
    price: "₹549",
    originalPrice: "₹3,299",
    image: "/placeholder.svg?height=400&width=600",
    premium: true,
    categoryId: "web-dev",
    topicIds: ["javascript"],
  },
  // React Courses
  {
    id: 9,
    title: "React - The Complete Guide (incl Hooks, React Router, Redux)",
    instructor: "Maximilian Schwarzmüller",
    rating: 4.7,
    reviews: 187654,
    price: "₹499",
    originalPrice: "₹3,499",
    image: "/placeholder.svg?height=400&width=600",
    premium: true,
    bestseller: true,
    categoryId: "web-dev",
    topicIds: ["react"],
  },
  {
    id: 10,
    title: "Modern React with Redux",
    instructor: "Stephen Grider",
    rating: 4.8,
    reviews: 98765,
    price: "₹549",
    originalPrice: "₹3,299",
    image: "/placeholder.svg?height=400&width=600",
    premium: true,
    categoryId: "web-dev",
    topicIds: ["react"],
  },
  {
    id: 11,
    title: "Complete React Developer in 2025 (w/ Redux, Hooks, GraphQL)",
    instructor: "Andrei Neagoie, Zero To Mastery",
    rating: 4.7,
    reviews: 45678,
    price: "₹499",
    originalPrice: "₹3,499",
    image: "/placeholder.svg?height=400&width=600",
    premium: true,
    categoryId: "web-dev",
    topicIds: ["react"],
  },
  {
    id: 12,
    title: "React Testing Library and Jest: The Complete Guide",
    instructor: "Stephen Grider",
    rating: 4.6,
    reviews: 12345,
    price: "₹449",
    originalPrice: "₹2,999",
    image: "/placeholder.svg?height=400&width=600",
    premium: true,
    categoryId: "web-dev",
    topicIds: ["react"],
  },
  // Angular Courses
  {
    id: 13,
    title: "Angular - The Complete Guide (2025 Edition)",
    instructor: "Maximilian Schwarzmüller",
    rating: 4.6,
    reviews: 156789,
    price: "₹499",
    originalPrice: "₹3,499",
    image: "/placeholder.svg?height=400&width=600",
    premium: true,
    bestseller: true,
    categoryId: "web-dev",
    topicIds: ["angular"],
  },
  {
    id: 14,
    title: "The Complete Angular Course: Beginner to Advanced",
    instructor: "Mosh Hamedani",
    rating: 4.5,
    reviews: 67890,
    price: "₹449",
    originalPrice: "₹2,999",
    image: "/placeholder.svg?height=400&width=600",
    premium: true,
    categoryId: "web-dev",
    topicIds: ["angular"],
  },
  // Data Science Courses
  {
    id: 17,
    title: "The Data Science Course 2025: Complete Data Science Bootcamp",
    instructor: "365 Careers Team",
    rating: 4.6,
    reviews: 156789,
    price: "₹499",
    originalPrice: "₹3,499",
    image: "/placeholder.svg?height=400&width=600",
    premium: true,
    bestseller: true,
    categoryId: "data-science",
    topicIds: ["data-science-general"],
  },
  {
    id: 18,
    title: "Python for Data Science and Machine Learning Bootcamp",
    instructor: "Jose Portilla",
    rating: 4.7,
    reviews: 187654,
    price: "₹549",
    originalPrice: "₹3,299",
    image: "/placeholder.svg?height=400&width=600",
    premium: true,
    categoryId: "data-science",
    topicIds: ["data-science-general", "python"],
  },
  // Python Courses
  {
    id: 21,
    title: "Complete Python Bootcamp From Zero to Hero in Python",
    instructor: "Jose Portilla",
    rating: 4.6,
    reviews: 456789,
    price: "₹499",
    originalPrice: "₹3,499",
    image: "/placeholder.svg?height=400&width=600",
    premium: true,
    bestseller: true,
    categoryId: "data-science",
    topicIds: ["python"],
  },
  {
    id: 22,
    title: "2025 Complete Python Mastery",
    instructor: "Mosh Hamedani",
    rating: 4.7,
    reviews: 98765,
    price: "₹449",
    originalPrice: "₹2,999",
    image: "/placeholder.svg?height=400&width=600",
    premium: true,
    categoryId: "data-science",
    topicIds: ["python"],
  },
  // IT Certification Courses
  {
    id: 29,
    title: "Ultimate AWS Certified Solutions Architect Associate 2025",
    instructor: "Stephane Maarek",
    rating: 4.7,
    reviews: 187654,
    price: "₹499",
    originalPrice: "₹3,499",
    image: "/placeholder.svg?height=400&width=600",
    premium: true,
    bestseller: true,
    categoryId: "it-cert",
    topicIds: ["aws"],
  },
  {
    id: 30,
    title: "AWS Certified Cloud Practitioner: Complete Course NEW 2025",
    instructor: "Stephane Maarek",
    rating: 4.8,
    reviews: 98765,
    price: "₹449",
    originalPrice: "₹2,999",
    image: "/placeholder.svg?height=400&width=600",
    premium: true,
    categoryId: "it-cert",
    topicIds: ["aws"],
  },
  // Business Analytics Courses
  {
    id: 37,
    title: "The Complete SQL Bootcamp: Go from Zero to Hero",
    instructor: "Jose Portilla",
    rating: 4.7,
    reviews: 156789,
    price: "₹449",
    originalPrice: "₹2,999",
    image: "/placeholder.svg?height=400&width=600",
    premium: true,
    bestseller: true,
    categoryId: "business-analytics",
    topicIds: ["sql"],
  },
  {
    id: 38,
    title: "SQL - MySQL for Data Analytics and Business Intelligence",
    instructor: "365 Careers",
    rating: 4.6,
    reviews: 98765,
    price: "₹499",
    originalPrice: "₹3,499",
    image: "/placeholder.svg?height=400&width=600",
    premium: true,
    categoryId: "business-analytics",
    topicIds: ["sql"],
  },
]

// Topics data
export const topics = [
  // Web Development Topics
  {
    id: "web-dev-general",
    name: "Web Development",
    learners: "13.3M+",
    categoryId: "web-dev",
  },
  {
    id: "javascript",
    name: "JavaScript",
    learners: "17.7M+",
    categoryId: "web-dev",
  },
  {
    id: "react",
    name: "React JS",
    learners: "8M+",
    categoryId: "web-dev",
  },
  {
    id: "angular",
    name: "Angular",
    learners: "4M+",
    categoryId: "web-dev",
  },
  // Data Science Topics
  {
    id: "data-science-general",
    name: "Data Science",
    learners: "9.5M+",
    categoryId: "data-science",
  },
  {
    id: "python",
    name: "Python",
    learners: "21.5M+",
    categoryId: "data-science",
  },
  {
    id: "machine-learning",
    name: "Machine Learning",
    learners: "7.2M+",
    categoryId: "data-science",
  },
  // IT Certification Topics
  {
    id: "aws",
    name: "AWS Certification",
    learners: "5.8M+",
    categoryId: "it-cert",
  },
  {
    id: "comptia",
    name: "CompTIA",
    learners: "3.2M+",
    categoryId: "it-cert",
  },
  // Business Analytics Topics
  {
    id: "sql",
    name: "SQL",
    learners: "8.7M+",
    categoryId: "business-analytics",
  },
  {
    id: "tableau",
    name: "Tableau",
    learners: "4.5M+",
    categoryId: "business-analytics",
  },
]

// Categories data
export const categories = [
  {
    id: "web-dev",
    name: "Web Development",
  },
  {
    id: "data-science",
    name: "Data Science",
  },
  {
    id: "it-cert",
    name: "IT Certifications",
  },
  {
    id: "leadership",
    name: "Leadership",
  },
  {
    id: "communication",
    name: "Communication",
  },
  {
    id: "business-analytics",
    name: "Business Analytics & Intelligence",
  },
]

// Helper functions to get data
export const getTopicsByCategoryId = (categoryId: string) => {
  return topics.filter((topic) => topic.categoryId === categoryId)
}

export const getCoursesByTopicId = (topicId: string) => {
  return courses.filter((course) => course.topicIds.includes(topicId))
}

export const getCoursesByCategoryId = (categoryId: string) => {
  return courses.filter((course) => course.categoryId === categoryId)
}

